<a href="https://colab.research.google.com/github/galaxy-kim/Python_note_backup/blob/main/02_jan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2023년 1월 첫 코딩수업
#Python
##빅데이터 마케팅 분석 전문가

In [2]:
a=123
b="abc"
print(type(a),type(b))
print(a,b)

<class 'int'> <class 'str'>
123 abc


In [3]:
List=["a","b","c"]
List

['a', 'b', 'c']

In [4]:
Tuple=("a","b","c")
Tuple

('a', 'b', 'c')

In [5]:
Dic={"경기도":"김포","강원도":"원주","충청도":"청주"}
Dic

{'경기도': '김포', '강원도': '원주', '충청도': '청주'}

In [6]:
score=20
if score>40:
    print("vip")
else :
    print("member")

member


In [8]:
for i in [1,2,3,4,5]:
    print(i)

1
2
3
4
5


In [10]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [12]:
customer_count=0
sum1=0
print("customer_count_sum")

while(sum1<20):
    customer_count=customer_count+1
    sum1=sum1+customer_count
    print(customer_count,sum1)

customer_count_sum
1 1
2 3
3 6
4 10
5 15
6 21


#Numpy

In [13]:
#Numpy

from matplotlib import pyplot as plt
from pandas import DataFrame
import numpy as np
from pandas import *

In [15]:
data = [1,2,3,4,5,6]
arr1=np.array(data)
arr1

array([1, 2, 3, 4, 5, 6])

In [16]:
arr1.dtype

dtype('int64')

In [18]:
arr1=np.arange(start=1,stop=20,step=2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
arr2=np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
arr1=np.array([10,12,14,16,18])
arr2=np.array([3,4,5,6,7])

print("**~더하기~**")
print(arr1+arr2)
print("*~~빼기~~*")
print(arr1-arr2)
print("**~곱하기~**")
print(arr1*arr2)
print("*~~나누기~~*")
print(arr1/arr2)

**~더하기~**
[13 16 19 22 25]
*~~빼기~~*
[ 7  8  9 10 11]
**~곱하기~**
[ 30  48  70  96 126]
*~~나누기~~*
[3.33333333 3.         2.8        2.66666667 2.57142857]


In [22]:
arr1=np.array([10,12,14,16,18,20])
arr2=np.array([3,4,5,6,7])

print("**~더하기~**")
print(arr1+arr2)
print("*~~빼기~~*")
print(arr1-arr2)
print("**~곱하기~**")
print(arr1*arr2)
print("*~~나누기~~*")
print(arr1/arr2)

**~더하기~**


ValueError: ignored

In [25]:
arr1[1]
arr1[0]


10

In [26]:
arr1[4]=20
print(arr1)

[10 12 14 16 20 20]


In [27]:
arr1[1,3,4]

IndexError: ignored

In [28]:
arr3=np.array([1,3,5,7,9,11])
arr3

array([ 1,  3,  5,  7,  9, 11])

In [29]:
arr3[1:5]

array([3, 5, 7, 9])

In [30]:
arr4=np.arange(10)
arr4=arr4.reshape(2,5)
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
arr4=np.arange(10)
arr4=arr4.reshape(2,5,1)
arr4

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [32]:
arr5=np.arange(20)
arr5=arr5.reshape(-1,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#Pandas
##데이터를 다루는 최적의 패키지!

In [35]:
import pandas as pd

In [36]:
series=pd.Series([1,2,3,4,5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [38]:
pd.DataFrame(series)
#DataFrame : 엑셀의 형태

0
0  1
1  2
2  3
3  4
4  5

In [39]:
col_list=["고객이름","나이","등급"]
val_list=[["유한별",34,"silver"],["강동원",40,"diamond"],["옥동자",45,"gold"]]
pd.DataFrame(data=val_list,columns=col_list)

고객이름  나이       등급
0  유한별  34   silver
1  강동원  40  diamond
2  옥동자  45     gold

In [40]:
col_list=["name","age","grade"]
val_list=[["유한별",34,"silver"],["강동원",40,"diamond"],["옥동자",45,"gold"]]
pd.DataFrame(data=val_list,columns=col_list)

name  age    grade
0  유한별   34   silver
1  강동원   40  diamond
2  옥동자   45     gold

In [41]:
dict={"고객이름":["유한별","강동원","옥동자"],"나이":[34,40,45],"등급":["silver","diamond","gold"]}
pd.DataFrame(data=dict)

#엑셀 import 하면 돼요~ 지금은 그냥 코딩하는 법 알아두기

고객이름  나이       등급
0  유한별  34   silver
1  강동원  40  diamond
2  옥동자  45     gold

In [43]:
sales_data={"화장품":[300,250,150,524,211],
            "의류":[170,182,193,324,487],
            "식품":[220,231,452,520,152],
            "전자제품":[500,345,152,540,290]}
col_list=["화장품","의류","식품","전자제품"]
index_list=["2017","2018","2019","2020","2021"]

df_sales=pd.DataFrame(data=sales_data,columns=col_list,index=index_list)
df_sales

#데이터가 있을 때, 행/열의 이름을 따로 붙여줄 수 있다다

화장품   의류   식품  전자제품
2017  300  170  220   500
2018  250  182  231   345
2019  150  193  452   152
2020  524  324  520   540
2021  211  487  152   290

In [44]:
print(df_sales.mean())

화장품     287.0
의류      271.2
식품      315.0
전자제품    365.4
dtype: float64


In [45]:
print(df_sales.std())

화장품     143.398047
의류      135.711827
식품      160.813557
전자제품    158.306033
dtype: float64


In [50]:
df_sales.describe()

화장품          의류          식품        전자제품
count    5.000000    5.000000    5.000000    5.000000
mean   287.000000  271.200000  315.000000  365.400000
std    143.398047  135.711827  160.813557  158.306033
min    150.000000  170.000000  152.000000  152.000000
25%    211.000000  182.000000  220.000000  290.000000
50%    250.000000  193.000000  231.000000  345.000000
75%    300.000000  324.000000  452.000000  500.000000
max    524.000000  487.000000  520.000000  540.000000

In [52]:
sales_data2={"화장품":[300,250,150,524,211,267,146],
            "의류":[170,182,193,324,487,502,810],
            "식품":[220,231,452,520,152,np.nan,np.nan],
            "전자제품":[500,345,152,540,290,125,318]}
col_list=["화장품","의류","식품","전자제품"]
index_list=["2017","2018","2019","2020","2021","2022","2023"]

df_sales2=pd.DataFrame(data=sales_data2,columns=col_list,index=index_list)
df_sales2

#결측치가 있는 데이터

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290
2022  267  502    NaN   125
2023  146  810    NaN   318

In [54]:
df_sales2.loc["2022"]

화장품     267.0
의류      502.0
식품        NaN
전자제품    125.0
Name: 2022, dtype: float64

In [56]:
df_sales2["식품"]["2022":"2023"]

2022   NaN
2023   NaN
Name: 식품, dtype: float64

In [57]:
df_sales2.loc["2022","식품"]

nan

In [60]:
df_sales2.iloc[2:4,0]
#컴퓨터(파이썬)가 잘 알아들을 수 있는 인덱스

2019    150
2020    524
Name: 화장품, dtype: int64

In [61]:
df_sales2.columns

Index(['화장품', '의류', '식품', '전자제품'], dtype='object')

In [64]:
df_sales2.isnull()
#null값 찾기

화장품     의류     식품   전자제품
2017  False  False  False  False
2018  False  False  False  False
2019  False  False  False  False
2020  False  False  False  False
2021  False  False  False  False
2022  False  False   True  False
2023  False  False   True  False

In [65]:
df_sales2.isnull().sum()

화장품     0
의류      0
식품      2
전자제품    0
dtype: int64

In [67]:
df_sales2_row=df_sales2.dropna(axis=0)
df_sales2_row
#결측값 제거(na가 있던 행 자체를 없애버림)

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290

In [68]:
df_sales2_col=df_sales2.dropna(axis=1)
df_sales2_col
#결측값 제거(na가 있던 열 자체를 없애버림)

화장품   의류  전자제품
2017  300  170   500
2018  250  182   345
2019  150  193   152
2020  524  324   540
2021  211  487   290
2022  267  502   125
2023  146  810   318

In [69]:
df_sales2_zero=df_sales2.fillna(0)
df_sales2_zero

#결측값 대체(0으로 대체)

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290
2022  267  502    0.0   125
2023  146  810    0.0   318

In [70]:
df_sales2_mean=df_sales2.fillna(df_sales2["식품"].mean())
df_sales2_mean

#결측값 대체("식품"에 대한 mean으로 대체)

화장품   의류     식품  전자제품
2017  300  170  220.0   500
2018  250  182  231.0   345
2019  150  193  452.0   152
2020  524  324  520.0   540
2021  211  487  152.0   290
2022  267  502  315.0   125
2023  146  810  315.0   318