<a href="https://colab.research.google.com/github/galaxy-kim/Python_note_backup/blob/main/230324_diet_df_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/ubion_given_data/online_diet_age_4.xlsx")
df

Unnamed: 0    id  age_code  occupation  sex  height  weight  married  \
0              0  3053         4           6    1   170.0    62.0        0   
1              1  3053         4           6    1   170.0    62.0        0   
2            173  3053         4           6    1   170.0    62.0        0   
3           4166  3053         4           6    1   170.0    62.0        0   
4           4167  3053         4           6    1   170.0    62.0        0   
...          ...   ...       ...         ...  ...     ...     ...      ...   
3045        2554  2144         4          15    2   158.0    52.0        0   
3046        2553   184         4          15    2   164.0    65.0        0   
3047        2552   627         4          15    2   165.0    54.0        0   
3048        2550  1334         4          12    2   165.0    59.0        0   
3049        2278   981         4          14    2   163.0    69.0        1   

      dise_yn  want_diet  ...  waist heap diet_purpose order_id  pfid  \
0           0       61.0  ...      0    0            3    16560   105   
1           0       61.0  ...      0    0            3    16926   105   
2           0       61.0  ...      0    0            3    17791   134   
3           0       61.0  ...      0    0            3    29442     9   
4           0       61.0  ...      0    0            3    29444     9   
...       ...        ...  ...    ...  ...          ...      ...   ...   
3045        1       47.0  ...     27   36            1     8149    39   
3046        1       48.0  ...     28    0            5     7451   108   
3047        1       48.0  ...      0    0            1     6873    21   
3048        0       55.0  ...     29    0            1     6526    12   
3049        1       55.0  ...     31   32            4    15305   135   

      p_category  p_price_000  p_month  bmi_g  p_price_000_idcount  
0              4           27        5      2                   64  
1              4           27        5      2                   64  
2              4           15        5      2                   64  
3              4            7        8      2                   64  
4              4            7        8      2                   64  
...          ...          ...      ...    ...                  ...  
3045           3           12        7      2                    1  
3046           4           12        7      3                    1  
3047           3           19        7      2                    1  
3048           3           39        7      2                    1  
3049           4           27        7      4                    1  

[3050 rows x 22 columns]

In [7]:
df=df.drop(['Unnamed: 0', 'age_code', 'created_YMD', 'order_id'],axis=1)

In [8]:
# convert column B to numeric and replace non-numeric values with NaN
df['waist'] = pd.to_numeric(df['waist'], errors='coerce')
df['heap'] = pd.to_numeric(df['heap'], errors='coerce')

# replace NaN values with the mean value of column B
mean_B = np.mean(df[['waist', 'heap']])
df[['waist', 'heap']] = df[['waist', 'heap']].fillna(mean_B)


/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   id                   3050 non-null   int64  
 1   occupation           3050 non-null   int64  
 2   sex                  3050 non-null   int64  
 3   height               3050 non-null   float64
 4   weight               3050 non-null   float64
 5   married              3050 non-null   int64  
 6   dise_yn              3050 non-null   int64  
 7   want_diet            3050 non-null   float64
 8   weight_reduce        3050 non-null   float64
 9   waist                3050 non-null   float64
 10  heap                 3050 non-null   float64
 11  diet_purpose         3050 non-null   int64  
 12  pfid                 3050 non-null   int64  
 13  p_category           3050 non-null   int64  
 14  p_price_000          3050 non-null   int64  
 15  p_month              3050 non-null   i

In [9]:
cg=df[['id','occupation', 'sex', 'married', 'dise_yn', 'diet_purpose','pfid', 'p_category', 'p_month', 'bmi_g']]
num=df[['height', 'weight', 'want_diet', 'weight_reduce', 'waist', 'heap', 'p_price_000','p_price_000_idcount']]

In [11]:
ndf=cg.join(num)

In [12]:

# define the bins and labels for grouping
bins = [0, 1, 4, 9, float('inf')]
labels = ['1', '2', '3', '4']
## 1 : 1회구매, 2 : 2~4회구매, 3 : 5~9회구매, 4 : 10회이상

# create a new column with the groups based on 'Purchasing Frequency'
ndf['idcount_code'] = pd.cut(ndf['p_price_000_idcount'], bins=bins, labels=labels)

# print the resulting dataframe
ndf


id  occupation  sex  married  dise_yn  diet_purpose  pfid  p_category  \
0     3053           6    1        0        0             3   105           4   
1     3053           6    1        0        0             3   105           4   
2     3053           6    1        0        0             3   134           4   
3     3053           6    1        0        0             3     9           4   
4     3053           6    1        0        0             3     9           4   
...    ...         ...  ...      ...      ...           ...   ...         ...   
3045  2144          15    2        0        1             1    39           3   
3046   184          15    2        0        1             5   108           4   
3047   627          15    2        0        1             1    21           3   
3048  1334          12    2        0        0             1    12           3   
3049   981          14    2        1        1             4   135           4   

      p_month  bmi_g  height  weight  want_diet  weight_reduce  waist  heap  \
0           5      2   170.0    62.0       61.0            1.0    0.0   0.0   
1           5      2   170.0    62.0       61.0            1.0    0.0   0.0   
2           5      2   170.0    62.0       61.0            1.0    0.0   0.0   
3           8      2   170.0    62.0       61.0            1.0    0.0   0.0   
4           8      2   170.0    62.0       61.0            1.0    0.0   0.0   
...       ...    ...     ...     ...        ...            ...    ...   ...   
3045        7      2   158.0    52.0       47.0            5.0   27.0  36.0   
3046        7      3   164.0    65.0       48.0           17.0   28.0   0.0   
3047        7      2   165.0    54.0       48.0            6.0    0.0   0.0   
3048        7      2   165.0    59.0       55.0            4.0   29.0   0.0   
3049        7      4   163.0    69.0       55.0           14.0   31.0  32.0   

      p_price_000  p_price_000_idcount idcount_code  
0              27                   64            4  
1              27                   64            4  
2              15                   64            4  
3               7                   64            4  
4               7                   64            4  
...           ...                  ...          ...  
3045           12                    1            1  
3046           12                    1            1  
3047           19                    1            1  
3048           39                    1            1  
3049           27                    1            1  

[3050 rows x 19 columns]

In [13]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   id                   3050 non-null   int64   
 1   occupation           3050 non-null   int64   
 2   sex                  3050 non-null   int64   
 3   married              3050 non-null   int64   
 4   dise_yn              3050 non-null   int64   
 5   diet_purpose         3050 non-null   int64   
 6   pfid                 3050 non-null   int64   
 7   p_category           3050 non-null   int64   
 8   p_month              3050 non-null   int64   
 9   bmi_g                3050 non-null   int64   
 10  height               3050 non-null   float64 
 11  weight               3050 non-null   float64 
 12  want_diet            3050 non-null   float64 
 13  weight_reduce        3050 non-null   float64 
 14  waist                3050 non-null   float64 
 15  heap                 

In [14]:
ndf.to_excel("/content/drive/MyDrive/Colab Notebooks/ubion_given_data/online_diet_40s.xlsx")


## 검정

In [19]:
import scipy as sp
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
     

### 등분산 "p_category", "p_month"

In [21]:
#등분산test(1)
#귀무가설: 등분산이다.
#대립가설: 등분산이 아니다.

ndf_anova = ndf[["p_category", "p_month"]]
pd.options.display.float_format = '{:.4f}'.format #결과값 소숫점을 4째자리까지

type1 = []
for i in range(1,5,1): #4개의 집단 평균비교(#1,2,3,4)
    type1.append(ndf_anova[ndf_anova.p_category==i].p_month)
sp.stats.levene(type1[0],type1[1],type1[2],type1[3])

#결과값
#pvalue =  (<0.05)
#대립가설 채택 -> '등분산 아니다'

LeveneResult(statistic=23.29417555540374, pvalue=6.638134150218026e-15)

In [24]:
!pip install pingouin
!pip install scikit_posthocs

import pingouin as pg
import scikit_posthocs

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.6/198.6 KB 4.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7048 sha256=6929273f511721bb20b4b96990c3f446a6bbfbf2b6d6d9f03f0e9650c9473bc8
  Stored in directory: /root/.cache/pip/wheels/04/bb/0d/2d02ec45f29c48d6192476bfb59c5a0e64b605e7212374dd15
Successfully built littleutils
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [25]:
#등분산test(2)
pg.homoscedasticity(dv= "p_month", group= "p_category", data = ndf)

#결과값
#pvalue =  (<0.05)
#대립가설 채택 -> '등분산 아니다'

W   pval  equal_var
levene 23.2942 0.0000      False

In [26]:
#ANOVA 검정(등분산이다)

model=ols("p_month~p_category",data=ndf).fit()
anova_lm(model)

df    sum_sq  mean_sq      F  PR(>F)
p_category    1.0000    8.1924   8.1924 8.5613  0.0035
Residual   3048.0000 2916.6587   0.9569    NaN     NaN

In [27]:
#ANOVA 검정(등분산아니다)

pg.welch_anova(dv="p_month",between="p_category",data=ndf)

Source  ddof1    ddof2       F  p-unc    np2
0  p_category      3 821.8822 17.9177 0.0000 0.0151

### 등분산 :: diet_purpose, dise_yn

In [28]:
#등분산test(1)
#귀무가설: 등분산이다.
#대립가설: 등분산이 아니다.

ndf_anova = ndf[["p_category", "diet_purpose"]]
pd.options.display.float_format = '{:.4f}'.format #결과값 소숫점을 4째자리까지

type1 = []
for i in range(1,5,1): #4개의 집단 평균비교(#1,2,3,4)
    type1.append(ndf_anova[ndf_anova.p_category==i].diet_purpose)
sp.stats.levene(type1[0],type1[1],type1[2],type1[3])

#결과값
#pvalue = 0.0248 (<0.05)
#대립가설 채택 -> '등분산 아니다'

LeveneResult(statistic=3.125329459832658, pvalue=0.024832973818705414)

In [29]:
#등분산test(2)
pg.homoscedasticity(dv= "diet_purpose", group= "p_category", data = ndf)

#결과값
#pvalue = 0.0248 (<0.05)
#대립가설 채택 -> '등분산 아니다'

W   pval  equal_var
levene 3.1253 0.0248      False

In [30]:
#등분산test(1)
#귀무가설: 등분산이다.
#대립가설: 등분산이 아니다.

ndf_anova = ndf[["p_category", "dise_yn"]]
pd.options.display.float_format = '{:.4f}'.format #결과값 소숫점을 4째자리까지

type1 = []
for i in range(1,5,1): #4개의 집단 평균비교(#1,2,3,4)
    type1.append(ndf_anova[ndf_anova.p_category==i].dise_yn)
sp.stats.levene(type1[0],type1[1],type1[2],type1[3])

#결과값
#pvalue = 0.1154 (>0.05)
#귀무가설 채택 -> '등분산이다'

LeveneResult(statistic=1.9754552760194157, pvalue=0.11548850781302568)

In [31]:
#등분산test(2)
pg.homoscedasticity(dv= "dise_yn", group= "p_category", data = ndf)

#결과값
#pvalue = 0.1155 (>0.05)
#귀무가설 채택 -> '등분산이다'

W   pval  equal_var
levene 1.9755 0.1155       True

## 모형

In [32]:
ndf.columns

Index(['id', 'occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'pfid',
       'p_category', 'p_month', 'bmi_g', 'height', 'weight', 'want_diet',
       'weight_reduce', 'waist', 'heap', 'p_price_000', 'p_price_000_idcount',
       'idcount_code'],
      dtype='object')

In [33]:
# Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


### 챗gpt 모델

In [34]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'p_month', 'bmi_g', 'height', 'weight', 'want_diet', 'p_price_000']]
y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Create and fit the logistic regression model
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = logreg.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

Accuracy: 0.5065573770491804
Confusion matrix: [[  0  20  23   9]
 [ 11  29  37   2]
 [  5   1 222  34]
 [  4   1 154  58]]


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
# Get the coefficients and corresponding feature names
coef = logreg.coef_[0]
features = X.columns

# Create a DataFrame of coefficients and features
coef_df = pd.DataFrame({'feature': features, 'coefficient': coef})

# Sort the coefficients by absolute value in descending order
coef_df['abs_coef'] = abs(coef_df['coefficient'])
sorted_coef = coef_df.sort_values('abs_coef', ascending=False)

# Print the sorted coefficients
print(sorted_coef)


         feature  coefficient  abs_coef
5        p_month       0.6278    0.6278
2        married       0.2925    0.2925
1            sex      -0.1442    0.1442
9      want_diet       0.1395    0.1395
6          bmi_g      -0.1296    0.1296
8         weight      -0.0748    0.0748
0     occupation      -0.0574    0.0574
7         height      -0.0497    0.0497
3        dise_yn       0.0487    0.0487
10   p_price_000       0.0248    0.0248
4   diet_purpose      -0.0099    0.0099


### 수업 코드 모델

In [40]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder 

In [43]:
from sklearn.metrics import classification_report

In [44]:

#다항 로지스틱 회귀분석
#-> 종속변수가 0,1(ex.이탈여부)이 아니고 더 여러개 3,4,5,6 처럼 다항으로 클래스가 나누어져있음
X = ndf[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'p_month', 'bmi_g', 'height', 'weight', 'want_diet', 'p_price_000']]
Y = ndf['p_category']

#데이터 분할
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.3, random_state= 0)

#Column transformer
#ct = ColumnTransformer([("scaling", StandardScaler(), ['height', 'weight', 'want_diet', 'p_price_000']),
                        #("onehot", OneHotEncoder(sparse=False), ['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'p_month', 'bmi_g'])])
#ct.fit(X_train)
#X_train = ct.transform(X_train)
#X_test = ct.transform(X_test)

#샘플링 생략했음#

#model
#multinomial -> '다항' 로지스틱 회귀
multilogit = LogisticRegression(random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial") 
#C의 값이 커지면 과적합/ 작아지면 모형 적합이 안됨
#'C=0.1' -> 과적합을 방지하기 위해 설정(원래는 C=1이 기본값)
##solver(어떤 가중치를 사용해서 해결할것인가): "lbfgs", "liblinear", "sag", "saga"
multilogit.fit(X_train, Y_train)
Y_pred = multilogit.predict(X_test)

#성능
print("r2 : {:.3f}".format(multilogit.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

r2 : 0.544
              precision    recall  f1-score   support

           1       0.22      0.07      0.10        76
           2       0.63      0.43      0.51       120
           3       0.49      0.85      0.62       386
           4       0.56      0.25      0.35       333

    accuracy                           0.51       915
   macro avg       0.48      0.40      0.40       915
weighted avg       0.52      0.51      0.47       915



### 변수 조정 모델링

In [47]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'bmi_g', 'want_diet']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg1 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg1.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg1.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg1.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

Accuracy: 0.43934426229508194
Confusion matrix: [[  1   0  63  12]
 [  1   0 115   4]
 [  6   0 367  13]
 [  5   0 294  34]]
r2 : 0.459
              precision    recall  f1-score   support

           1       0.08      0.01      0.02        76
           2       0.00      0.00      0.00       120
           3       0.44      0.95      0.60       386
           4       0.54      0.10      0.17       333

    accuracy                           0.44       915
   macro avg       0.26      0.27      0.20       915
weighted avg       0.39      0.44      0.32       915



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
# Extract the coefficients and feature names
coefs = lg1.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

        feature  coefficient  abs_coef
1           sex       0.3240    0.3240
2       married       0.2516    0.2516
5         bmi_g      -0.0860    0.0860
0    occupation      -0.0627    0.0627
6     want_diet       0.0607    0.0607
3       dise_yn       0.0435    0.0435
4  diet_purpose       0.0087    0.0087


In [52]:

# Load the data
data = ndf

# Prepare the data
X = data[['bmi_g', 'want_diet', 'waist', 'heap', 'weight_reduce', 'idcount_code']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg2 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg2.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg2.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg2.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

Accuracy: 0.4273224043715847
Confusion matrix: [[  0   0  62  14]
 [  1   0 114   5]
 [  4   0 357  25]
 [  4   0 295  34]]
r2 : 0.455
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        76
           2       0.00      0.00      0.00       120
           3       0.43      0.92      0.59       386
           4       0.44      0.10      0.17       333

    accuracy                           0.43       915
   macro avg       0.22      0.26      0.19       915
weighted avg       0.34      0.43      0.31       915



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [53]:
# Extract the coefficients and feature names
coefs = lg2.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

          feature  coefficient  abs_coef
6  idcount_code_2      -0.2824    0.2824
0           bmi_g       0.2244    0.2244
8  idcount_code_4       0.1487    0.1487
7  idcount_code_3       0.0996    0.0996
4   weight_reduce      -0.0674    0.0674
5  idcount_code_1       0.0341    0.0341
1       want_diet       0.0295    0.0295
2           waist       0.0013    0.0013
3            heap       0.0004    0.0004


In [57]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'bmi_g', 'want_diet', 'p_category']]
Y = data['idcount_code']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg3 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg3.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg3.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg3.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

Accuracy: 0.5606557377049181
Confusion matrix: [[503   1   0   2]
 [357   2   0   2]
 [ 24   0   0   0]
 [ 16   0   0   8]]
r2 : 0.612
              precision    recall  f1-score   support

           1       0.56      0.99      0.72       506
           2       0.67      0.01      0.01       361
           3       0.00      0.00      0.00        24
           4       0.67      0.33      0.44        24

    accuracy                           0.56       915
   macro avg       0.47      0.33      0.29       915
weighted avg       0.59      0.56      0.41       915



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [58]:
# Extract the coefficients and feature names
coefs = lg3.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

        feature  coefficient  abs_coef
1           sex       0.6816    0.6816
2       married      -0.1149    0.1149
5         bmi_g       0.1041    0.1041
7    p_category      -0.0576    0.0576
4  diet_purpose      -0.0555    0.0555
3       dise_yn      -0.0059    0.0059
0    occupation      -0.0016    0.0016
6     want_diet       0.0004    0.0004
