<a href="https://colab.research.google.com/github/galaxy-kim/Python_note_backup/blob/main/230324_diet_df_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

## data

In [7]:
df=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/ubion_given_data/online_diet_40s.xlsx")
df

Unnamed: 0    id  occupation  sex  married  dise_yn  diet_purpose  pfid  \
0              0  3053           6    1        0        0             3   105   
1              1  3053           6    1        0        0             3   105   
2              2  3053           6    1        0        0             3   134   
3              3  3053           6    1        0        0             3     9   
4              4  3053           6    1        0        0             3     9   
...          ...   ...         ...  ...      ...      ...           ...   ...   
3045        3045  2144          15    2        0        1             1    39   
3046        3046   184          15    2        0        1             5   108   
3047        3047   627          15    2        0        1             1    21   
3048        3048  1334          12    2        0        0             1    12   
3049        3049   981          14    2        1        1             4   135   

      p_category  p_month  bmi_g  height  weight  want_diet  weight_reduce  \
0              4        5      2   170.0    62.0       61.0            1.0   
1              4        5      2   170.0    62.0       61.0            1.0   
2              4        5      2   170.0    62.0       61.0            1.0   
3              4        8      2   170.0    62.0       61.0            1.0   
4              4        8      2   170.0    62.0       61.0            1.0   
...          ...      ...    ...     ...     ...        ...            ...   
3045           3        7      2   158.0    52.0       47.0            5.0   
3046           4        7      3   164.0    65.0       48.0           17.0   
3047           3        7      2   165.0    54.0       48.0            6.0   
3048           3        7      2   165.0    59.0       55.0            4.0   
3049           4        7      4   163.0    69.0       55.0           14.0   

      waist  heap  p_price_000  p_price_000_idcount  idcount_code  
0       0.0   0.0           27                   64             4  
1       0.0   0.0           27                   64             4  
2       0.0   0.0           15                   64             4  
3       0.0   0.0            7                   64             4  
4       0.0   0.0            7                   64             4  
...     ...   ...          ...                  ...           ...  
3045   27.0  36.0           12                    1             1  
3046   28.0   0.0           12                    1             1  
3047    0.0   0.0           19                    1             1  
3048   29.0   0.0           39                    1             1  
3049   31.0  32.0           27                    1             1  

[3050 rows x 20 columns]

In [8]:
df=df.drop(['Unnamed: 0'],axis=1)

In [9]:
cg=df[['id','occupation', 'sex', 'married', 'dise_yn', 'diet_purpose','pfid', 'p_category', 'p_month', 'bmi_g']]
num=df[['height', 'weight', 'want_diet', 'weight_reduce', 'waist', 'heap', 'p_price_000','p_price_000_idcount']]

In [10]:
ndf=cg.join(num)

In [16]:
# define the bins and labels for grouping
bins = [0, 1, 4, 9, float('inf')]
labels = ['1', '2', '3', '4']
## 1 : 1회구매, 2 : 2~4회구매, 3 : 5~9회구매, 4 : 10회이상

# create a new column with the groups based on 'Purchasing Frequency'
ndf['idcount_code'] = pd.cut(ndf['p_price_000_idcount'], bins=bins, labels=labels)

# print the resulting dataframe
ndf

id  occupation  sex  married  dise_yn  diet_purpose  pfid  p_category  \
0     3053           6    1        0        0             3   105           4   
1     3053           6    1        0        0             3   105           4   
2     3053           6    1        0        0             3   134           4   
3     3053           6    1        0        0             3     9           4   
4     3053           6    1        0        0             3     9           4   
...    ...         ...  ...      ...      ...           ...   ...         ...   
3045  2144          15    2        0        1             1    39           3   
3046   184          15    2        0        1             5   108           4   
3047   627          15    2        0        1             1    21           3   
3048  1334          12    2        0        0             1    12           3   
3049   981          14    2        1        1             4   135           4   

      p_month  bmi_g  height  weight  want_diet  weight_reduce  waist  heap  \
0           5      2   170.0    62.0       61.0            1.0    0.0   0.0   
1           5      2   170.0    62.0       61.0            1.0    0.0   0.0   
2           5      2   170.0    62.0       61.0            1.0    0.0   0.0   
3           8      2   170.0    62.0       61.0            1.0    0.0   0.0   
4           8      2   170.0    62.0       61.0            1.0    0.0   0.0   
...       ...    ...     ...     ...        ...            ...    ...   ...   
3045        7      2   158.0    52.0       47.0            5.0   27.0  36.0   
3046        7      3   164.0    65.0       48.0           17.0   28.0   0.0   
3047        7      2   165.0    54.0       48.0            6.0    0.0   0.0   
3048        7      2   165.0    59.0       55.0            4.0   29.0   0.0   
3049        7      4   163.0    69.0       55.0           14.0   31.0  32.0   

      p_price_000  p_price_000_idcount idcount_code  
0              27                   64            4  
1              27                   64            4  
2              15                   64            4  
3               7                   64            4  
4               7                   64            4  
...           ...                  ...          ...  
3045           12                    1            1  
3046           12                    1            1  
3047           19                    1            1  
3048           39                    1            1  
3049           27                    1            1  

[3050 rows x 19 columns]

## logistic regression 모형

In [ ]:
ndf.columns

Index(['id', 'occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'pfid',
       'p_category', 'p_month', 'bmi_g', 'height', 'weight', 'want_diet',
       'weight_reduce', 'waist', 'heap', 'p_price_000', 'p_price_000_idcount',
       'idcount_code'],
      dtype='object')

In [12]:
# Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix

### 챗gpt 모델

In [ ]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'p_month', 'bmi_g', 'height', 'weight', 'want_diet', 'p_price_000']]
y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Create and fit the logistic regression model
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = logreg.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

Accuracy: 0.5065573770491804
Confusion matrix: [[  0  20  23   9]
 [ 11  29  37   2]
 [  5   1 222  34]
 [  4   1 154  58]]


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# Get the coefficients and corresponding feature names
coef = logreg.coef_[0]
features = X.columns

# Create a DataFrame of coefficients and features
coef_df = pd.DataFrame({'feature': features, 'coefficient': coef})

# Sort the coefficients by absolute value in descending order
coef_df['abs_coef'] = abs(coef_df['coefficient'])
sorted_coef = coef_df.sort_values('abs_coef', ascending=False)

# Print the sorted coefficients
print(sorted_coef)


         feature  coefficient  abs_coef
5        p_month       0.6278    0.6278
2        married       0.2925    0.2925
1            sex      -0.1442    0.1442
9      want_diet       0.1395    0.1395
6          bmi_g      -0.1296    0.1296
8         weight      -0.0748    0.0748
0     occupation      -0.0574    0.0574
7         height      -0.0497    0.0497
3        dise_yn       0.0487    0.0487
10   p_price_000       0.0248    0.0248
4   diet_purpose      -0.0099    0.0099


### 수업 코드 모델

In [13]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder 

In [14]:
from sklearn.metrics import classification_report

In [ ]:

#다항 로지스틱 회귀분석
#-> 종속변수가 0,1(ex.이탈여부)이 아니고 더 여러개 3,4,5,6 처럼 다항으로 클래스가 나누어져있음
X = ndf[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'p_month', 'bmi_g', 'height', 'weight', 'want_diet', 'p_price_000']]
Y = ndf['p_category']

#데이터 분할
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.3, random_state= 0)

#Column transformer
#ct = ColumnTransformer([("scaling", StandardScaler(), ['height', 'weight', 'want_diet', 'p_price_000']),
                        #("onehot", OneHotEncoder(sparse=False), ['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'p_month', 'bmi_g'])])
#ct.fit(X_train)
#X_train = ct.transform(X_train)
#X_test = ct.transform(X_test)

#샘플링 생략했음#

#model
#multinomial -> '다항' 로지스틱 회귀
multilogit = LogisticRegression(random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial") 
#C의 값이 커지면 과적합/ 작아지면 모형 적합이 안됨
#'C=0.1' -> 과적합을 방지하기 위해 설정(원래는 C=1이 기본값)
##solver(어떤 가중치를 사용해서 해결할것인가): "lbfgs", "liblinear", "sag", "saga"
multilogit.fit(X_train, Y_train)
Y_pred = multilogit.predict(X_test)

#성능
print("r2 : {:.3f}".format(multilogit.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

r2 : 0.544
              precision    recall  f1-score   support

           1       0.22      0.07      0.10        76
           2       0.63      0.43      0.51       120
           3       0.49      0.85      0.62       386
           4       0.56      0.25      0.35       333

    accuracy                           0.51       915
   macro avg       0.48      0.40      0.40       915
weighted avg       0.52      0.51      0.47       915



### 변수 조정 모델링

#### 'occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'bmi_g', 'want_diet' :: 'p_category'

In [ ]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'bmi_g', 'want_diet']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg1 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg1.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg1.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg1.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

Accuracy: 0.43934426229508194
Confusion matrix: [[  1   0  63  12]
 [  1   0 115   4]
 [  6   0 367  13]
 [  5   0 294  34]]
r2 : 0.459
              precision    recall  f1-score   support

           1       0.08      0.01      0.02        76
           2       0.00      0.00      0.00       120
           3       0.44      0.95      0.60       386
           4       0.54      0.10      0.17       333

    accuracy                           0.44       915
   macro avg       0.26      0.27      0.20       915
weighted avg       0.39      0.44      0.32       915



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Extract the coefficients and feature names
coefs = lg1.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

        feature  coefficient  abs_coef
1           sex       0.3240    0.3240
2       married       0.2516    0.2516
5         bmi_g      -0.0860    0.0860
0    occupation      -0.0627    0.0627
6     want_diet       0.0607    0.0607
3       dise_yn       0.0435    0.0435
4  diet_purpose       0.0087    0.0087


#### 'bmi_g', 'want_diet', 'waist', 'heap', 'weight_reduce', 'idcount_code' :: 'p_category'

In [ ]:

# Load the data
data = ndf

# Prepare the data
X = data[['bmi_g', 'want_diet', 'waist', 'heap', 'weight_reduce', 'idcount_code']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg2 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg2.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg2.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg2.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

Accuracy: 0.4273224043715847
Confusion matrix: [[  0   0  62  14]
 [  1   0 114   5]
 [  4   0 357  25]
 [  4   0 295  34]]
r2 : 0.455
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        76
           2       0.00      0.00      0.00       120
           3       0.43      0.92      0.59       386
           4       0.44      0.10      0.17       333

    accuracy                           0.43       915
   macro avg       0.22      0.26      0.19       915
weighted avg       0.34      0.43      0.31       915



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Extract the coefficients and feature names
coefs = lg2.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

          feature  coefficient  abs_coef
6  idcount_code_2      -0.2824    0.2824
0           bmi_g       0.2244    0.2244
8  idcount_code_4       0.1487    0.1487
7  idcount_code_3       0.0996    0.0996
4   weight_reduce      -0.0674    0.0674
5  idcount_code_1       0.0341    0.0341
1       want_diet       0.0295    0.0295
2           waist       0.0013    0.0013
3            heap       0.0004    0.0004


#### 'occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'bmi_g', 'want_diet', 'p_category' :: 'idcount_code'

In [ ]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'bmi_g', 'want_diet', 'p_category']]
Y = data['idcount_code']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg3 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg3.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg3.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg3.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

Accuracy: 0.5606557377049181
Confusion matrix: [[503   1   0   2]
 [357   2   0   2]
 [ 24   0   0   0]
 [ 16   0   0   8]]
r2 : 0.612
              precision    recall  f1-score   support

           1       0.56      0.99      0.72       506
           2       0.67      0.01      0.01       361
           3       0.00      0.00      0.00        24
           4       0.67      0.33      0.44        24

    accuracy                           0.56       915
   macro avg       0.47      0.33      0.29       915
weighted avg       0.59      0.56      0.41       915



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Extract the coefficients and feature names
coefs = lg3.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

        feature  coefficient  abs_coef
1           sex       0.6816    0.6816
2       married      -0.1149    0.1149
5         bmi_g       0.1041    0.1041
7    p_category      -0.0576    0.0576
4  diet_purpose      -0.0555    0.0555
3       dise_yn      -0.0059    0.0059
0    occupation      -0.0016    0.0016
6     want_diet       0.0004    0.0004


#### ::

In [17]:
ndf.columns

Index(['id', 'occupation', 'sex', 'married', 'dise_yn', 'diet_purpose', 'pfid',
       'p_category', 'p_month', 'bmi_g', 'height', 'weight', 'want_diet',
       'weight_reduce', 'waist', 'heap', 'p_price_000', 'p_price_000_idcount',
       'idcount_code'],
      dtype='object')

In [24]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married', 'dise_yn', 'diet_purpose',
       'bmi_g', 'height', 'weight', 'want_diet',
       'weight_reduce', 'waist', 'heap', 'p_price_000', 'p_price_000_idcount',
       'idcount_code']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg4 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg4.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg4.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg4.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))

Accuracy: 0.5147540983606558
Confusion matrix: [[  7  24  34  11]
 [  5  54  60   1]
 [  4   3 329  50]
 [  7   2 243  81]]
r2 : 0.527
              precision    recall  f1-score   support

           1       0.30      0.09      0.14        76
           2       0.65      0.45      0.53       120
           3       0.49      0.85      0.63       386
           4       0.57      0.24      0.34       333

    accuracy                           0.51       915
   macro avg       0.50      0.41      0.41       915
weighted avg       0.53      0.51      0.47       915



In [21]:
# Extract the coefficients and feature names
coefs = lg4.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

                feature  coefficient  abs_coef
1                   sex     0.359984  0.359984
15       idcount_code_2    -0.272747  0.272747
2               married     0.214573  0.214573
14       idcount_code_1     0.205787  0.205787
16       idcount_code_3     0.076449  0.076449
5                 bmi_g     0.065540  0.065540
9         weight_reduce    -0.065133  0.065133
3               dise_yn     0.060993  0.060993
8             want_diet     0.058432  0.058432
0            occupation    -0.049825  0.049825
4          diet_purpose     0.027939  0.027939
12          p_price_000     0.021805  0.021805
6                height    -0.011784  0.011784
17       idcount_code_4    -0.009491  0.009491
7                weight    -0.006701  0.006701
13  p_price_000_idcount     0.005101  0.005101
10                waist     0.002028  0.002028
11                 heap     0.000640  0.000640


## 모델별 비교

#### 로지스틱 회귀 5~7

In [25]:

# Load the data
data = ndf

# Prepare the data
X = data[['occupation', 'sex', 'married','dise_yn', 'diet_purpose']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg5 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg5.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg5.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg5.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))


# Extract the coefficients and feature names
coefs = lg5.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

Accuracy: 0.43934426229508194
Confusion matrix: [[  0   0  68   8]
 [  0   0 114   6]
 [  0   0 373  13]
 [  0   0 304  29]]
r2 : 0.457
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        76
           2       0.00      0.00      0.00       120
           3       0.43      0.97      0.60       386
           4       0.52      0.09      0.15       333

    accuracy                           0.44       915
   macro avg       0.24      0.26      0.19       915
weighted avg       0.37      0.44      0.31       915

        feature  coefficient  abs_coef
2       married     0.293709  0.293709
0    occupation    -0.061112  0.061112
3       dise_yn    -0.029000  0.029000
1           sex    -0.028126  0.028126
4  diet_purpose     0.017868  0.017868


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:

# Load the data
data = ndf

# Prepare the data
X = data[['bmi_g', 'height', 'weight', 'want_diet','weight_reduce', 'waist', 'heap']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg6 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg6.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg6.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg6.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))


# Extract the coefficients and feature names
coefs = lg6.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

Accuracy: 0.43278688524590164
Confusion matrix: [[  0   0  61  15]
 [  1   0 115   4]
 [  4   1 361  20]
 [  4   0 294  35]]
r2 : 0.463
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        76
           2       0.00      0.00      0.00       120
           3       0.43      0.94      0.59       386
           4       0.47      0.11      0.17       333

    accuracy                           0.43       915
   macro avg       0.23      0.26      0.19       915
weighted avg       0.36      0.43      0.31       915

         feature  coefficient  abs_coef
0          bmi_g     0.102049  0.102049
4  weight_reduce    -0.052704  0.052704
3      want_diet     0.048053  0.048053
1         height    -0.014722  0.014722
2         weight    -0.004650  0.004650
6           heap     0.000471  0.000471
5          waist     0.000073  0.000073


In [28]:

# Load the data
data = ndf

# Prepare the data
X = data[['p_price_000', 'p_price_000_idcount']]
Y = data['p_category']

# Encode categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# Create and fit the logistic regression model
lg7 = LogisticRegression(max_iter=1000, random_state=0, C=0.1, solver='newton-cg', multi_class="multinomial")
lg7.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = lg7.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
confusion = confusion_matrix(Y_test, Y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:', confusion)

#성능
print("r2 : {:.3f}".format(lg7.score(X_train, Y_train)))
print(classification_report(Y_test, Y_pred))


# Extract the coefficients and feature names
coefs = lg7.coef_
feature_names = X.columns

# Combine the coefficients and feature names into a dataframe for easy viewing
coefs_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': coefs[0],
    'abs_coef': np.abs(coefs[0])
})

# Sort the dataframe by absolute value of coefficients (largest to smallest)
coefs_df = coefs_df.sort_values('abs_coef', ascending=False)

# View the top features by absolute coefficient value
print(coefs_df)

Accuracy: 0.4885245901639344
Confusion matrix: [[  2  28  42   4]
 [  3  53  63   1]
 [  1   2 375   8]
 [  0   4 312  17]]
r2 : 0.507
              precision    recall  f1-score   support

           1       0.33      0.03      0.05        76
           2       0.61      0.44      0.51       120
           3       0.47      0.97      0.64       386
           4       0.57      0.05      0.09       333

    accuracy                           0.49       915
   macro avg       0.50      0.37      0.32       915
weighted avg       0.51      0.49      0.37       915

               feature  coefficient  abs_coef
0          p_price_000     0.021450  0.021450
1  p_price_000_idcount     0.008593  0.008593


### KNN

In [29]:
from sklearn.neighbors import KNeighborsClassifier


In [30]:
from imblearn.over_sampling import SMOTE

In [31]:
#KNeighborsClassifier
#y값 = classification(분류)형

X = data[['occupation', 'sex', 'married','dise_yn', 'diet_purpose']]
Y = data['p_category']

#데이터 분할
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.3, random_state= 0)

#sclaer
scaler = StandardScaler().fit(X_train, Y_train)
X_test = scaler.transform(X_test)
X_train = scaler.transform(X_train)

#이탈여부 오버샘플링
X_train, Y_train = SMOTE(random_state = 0).fit_resample(X_train, Y_train)

#knn_model 생성
knn_model = KNeighborsClassifier(n_neighbors=9, metric="euclidean") 
#'classifier': 분류모델/ 'n_neighbors = 9' -> 근처에 있는 9개(임의의 수)의 neighbor를 찾는다
#'euclidean'거리 사용; 새로운 데이터와 가장 가까이 있는 값 사이의 거리

knn_model.fit(X_train, Y_train)
Y_pred = knn_model.predict(X_test)
print("accuracy : {:.3f}".format(knn_model.score(X_train, Y_train)))
print(classification_report(Y_pred, Y_test))

#결과값 -> accuracy와 f1-score값을 보면 됨
#위에 나온 accuracy -> train한 값의 정확도
#표안의 accuracy -> 예측값의 정확도
#범주별 f1-score 각각을 더해서 평균을 낸것이 f1-score

accuracy : 0.383
              precision    recall  f1-score   support

           1       0.07      0.10      0.08        49
           2       0.08      0.13      0.10        76
           3       0.66      0.42      0.51       602
           4       0.20      0.35      0.25       188

    accuracy                           0.37       915
   macro avg       0.25      0.25      0.24       915
weighted avg       0.48      0.37      0.40       915



In [32]:
#KNeighborsClassifier
#y값 = classification(분류)형

X = data[['bmi_g', 'height', 'weight', 'want_diet','weight_reduce', 'waist', 'heap']]
Y = data['p_category']

#데이터 분할
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.3, random_state= 0)

#sclaer
scaler = StandardScaler().fit(X_train, Y_train)
X_test = scaler.transform(X_test)
X_train = scaler.transform(X_train)

#이탈여부 오버샘플링
X_train, Y_train = SMOTE(random_state = 0).fit_resample(X_train, Y_train)

#knn_model 생성
knn_model = KNeighborsClassifier(n_neighbors=9, metric="euclidean") 
#'classifier': 분류모델/ 'n_neighbors = 9' -> 근처에 있는 9개(임의의 수)의 neighbor를 찾는다
#'euclidean'거리 사용; 새로운 데이터와 가장 가까이 있는 값 사이의 거리

knn_model.fit(X_train, Y_train)
Y_pred = knn_model.predict(X_test)
print("accuracy : {:.3f}".format(knn_model.score(X_train, Y_train)))
print(classification_report(Y_pred, Y_test))

#결과값 -> accuracy와 f1-score값을 보면 됨
#위에 나온 accuracy -> train한 값의 정확도
#표안의 accuracy -> 예측값의 정확도
#범주별 f1-score 각각을 더해서 평균을 낸것이 f1-score

accuracy : 0.649
              precision    recall  f1-score   support

           1       0.53      0.19      0.28       212
           2       0.40      0.20      0.26       243
           3       0.33      0.53      0.41       240
           4       0.29      0.45      0.35       220

    accuracy                           0.34       915
   macro avg       0.39      0.34      0.33       915
weighted avg       0.39      0.34      0.33       915



### 의사결정나무

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
X = data[['occupation', 'sex', 'married','dise_yn', 'diet_purpose']]
Y = data['p_category']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)


DT_model=DecisionTreeClassifier(random_state=0,max_depth=3) #깊이=층
DT_model.fit(X_train,Y_train)
Y_pred=DT_model.predict(X_test)
print("accurary : {:.3f}".format(DT_model.score(X_train,Y_train)))
print(classification_report(Y_test,Y_pred))

accurary : 0.339
              precision    recall  f1-score   support

           1       0.10      0.41      0.16        76
           2       0.13      0.20      0.16       120
           3       0.45      0.39      0.42       386
           4       0.35      0.08      0.14       333

    accuracy                           0.26       915
   macro avg       0.26      0.27      0.22       915
weighted avg       0.35      0.26      0.26       915



In [35]:
#feature importance (변수 중요도) : 변수의 영향 확인(가중치β와 유사)
feature_name=X.columns
feature_importance=DT_model.feature_importances_
sorted(zip(feature_importance,feature_name),reverse=True)

[(0.717563842949815, 'occupation'),
 (0.22975767746672376, 'diet_purpose'),
 (0.05267847958346117, 'sex'),
 (0.0, 'married'),
 (0.0, 'dise_yn')]

In [36]:
X = data[['bmi_g', 'height', 'weight', 'want_diet','weight_reduce', 'waist', 'heap']]
Y = data['p_category']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)


DT_model=DecisionTreeClassifier(random_state=0,max_depth=3) #깊이=층
DT_model.fit(X_train,Y_train)
Y_pred=DT_model.predict(X_test)
print("accurary : {:.3f}".format(DT_model.score(X_train,Y_train)))
print(classification_report(Y_test,Y_pred))

accurary : 0.407
              precision    recall  f1-score   support

           1       0.17      0.64      0.27        76
           2       0.14      0.46      0.21       120
           3       0.50      0.15      0.23       386
           4       0.47      0.14      0.22       333

    accuracy                           0.23       915
   macro avg       0.32      0.35      0.23       915
weighted avg       0.41      0.23      0.23       915



In [37]:
#feature importance (변수 중요도) : 변수의 영향 확인(가중치β와 유사)
feature_name=X.columns
feature_importance=DT_model.feature_importances_
sorted(zip(feature_importance,feature_name),reverse=True)

[(0.5535837282357364, 'want_diet'),
 (0.26713090737294265, 'weight_reduce'),
 (0.179285364391321, 'height'),
 (0.0, 'weight'),
 (0.0, 'waist'),
 (0.0, 'heap'),
 (0.0, 'bmi_g')]

### SVM

In [38]:
from sklearn.svm import SVC

In [47]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.inspection import permutation_importance


In [44]:
X = data[['occupation', 'sex', 'married','dise_yn', 'diet_purpose']]
Y = data['p_category']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)

SVC_model=SVC(C=1000,gamma=10,random_state=0)
SVC_model.fit(X_train,Y_train)
Y_pred=SVC_model.predict(X_test)
print("accurary : {:.3f}".format(SVC_model.score(X_train,Y_train)))
print(classification_report(Y_test,Y_pred))

accurary : 0.445
              precision    recall  f1-score   support

           1       0.11      0.30      0.16        76
           2       0.13      0.25      0.17       120
           3       0.38      0.09      0.15       386
           4       0.39      0.44      0.42       333

    accuracy                           0.26       915
   macro avg       0.25      0.27      0.22       915
weighted avg       0.33      0.26      0.25       915



In [49]:
# Use permutation importance to calculate feature importances
result = permutation_importance(SVC_model, X_test, Y_test, n_repeats=10, random_state=42, n_jobs=-1)

# Print the feature importances
for i in result.importances_mean.argsort()[::-1]:
    print(f"{i+1}. {X_train.columns[i]}: {result.importances_mean[i]:.3f}")

2. sex: -0.000
5. diet_purpose: -0.005
3. married: -0.007
1. occupation: -0.013
4. dise_yn: -0.027


In [50]:
X = data[['bmi_g', 'height', 'weight', 'want_diet','weight_reduce', 'waist', 'heap']]
Y = data['p_category']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)

SVC_model=SVC(C=1000,gamma=10,random_state=0)
SVC_model.fit(X_train,Y_train)
Y_pred=SVC_model.predict(X_test)
print("accurary : {:.3f}".format(SVC_model.score(X_train,Y_train)))
print(classification_report(Y_test,Y_pred))

accurary : 0.937
              precision    recall  f1-score   support

           1       0.33      0.18      0.24        76
           2       0.47      0.23      0.31       120
           3       0.48      0.88      0.62       386
           4       0.63      0.22      0.32       333

    accuracy                           0.49       915
   macro avg       0.48      0.38      0.37       915
weighted avg       0.52      0.49      0.44       915



In [51]:
# Use permutation importance to calculate feature importances
result = permutation_importance(SVC_model, X_test, Y_test, n_repeats=10, random_state=42, n_jobs=-1)

# Print the feature importances
for i in result.importances_mean.argsort()[::-1]:
    print(f"{i+1}. {X_train.columns[i]}: {result.importances_mean[i]:.3f}")

2. height: 0.069
4. want_diet: 0.068
3. weight: 0.068
5. weight_reduce: 0.064
6. waist: 0.059
7. heap: 0.044
1. bmi_g: 0.038


### Naive Bayes

In [52]:
from sklearn.naive_bayes import GaussianNB

In [53]:
X = data[['occupation', 'sex', 'married','dise_yn', 'diet_purpose']]
Y = data['p_category']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)

NB_model=GaussianNB(var_smoothing=0)
NB_model.fit(X_train,Y_train)
Y_pred=NB_model.predict(X_test)
print("accurary : {:.3f}".format(NB_model.score(X_train,Y_train)))
print(classification_report(Y_test,Y_pred))

accurary : 0.276
              precision    recall  f1-score   support

           1       0.10      0.09      0.10        76
           2       0.12      0.76      0.21       120
           3       0.29      0.03      0.05       386
           4       0.47      0.10      0.16       333

    accuracy                           0.15       915
   macro avg       0.25      0.24      0.13       915
weighted avg       0.32      0.15      0.12       915



In [54]:
X = data[['bmi_g', 'height', 'weight', 'want_diet','weight_reduce', 'waist', 'heap']]
Y = data['p_category']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)

NB_model=GaussianNB(var_smoothing=0)
NB_model.fit(X_train,Y_train)
Y_pred=NB_model.predict(X_test)
print("accurary : {:.3f}".format(NB_model.score(X_train,Y_train)))
print(classification_report(Y_test,Y_pred))

accurary : 0.403
              precision    recall  f1-score   support

           1       0.19      0.72      0.30        76
           2       0.19      0.28      0.22       120
           3       0.48      0.52      0.50       386
           4       0.33      0.04      0.07       333

    accuracy                           0.33       915
   macro avg       0.30      0.39      0.28       915
weighted avg       0.37      0.33      0.29       915



### gradient boost

In [56]:
from sklearn.ensemble import GradientBoostingClassifier

In [58]:
#1.변수선택
X = data[['occupation', 'sex', 'married','dise_yn', 'diet_purpose']]
Y = data['p_category']

#2.데이터 전처리(preprocessing)
X = pd.get_dummies(X)

#3.train-test split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

#4.오버샘플링
smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)

#5.모형생성
model=GradientBoostingClassifier(random_state=0,n_estimators=100,max_depth=4,learning_rate=0.1)

#6.모형학습 예측
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
print("accuracy(test) : {:.3f}".format(model.score(X_test,Y_test)))
print(classification_report(Y_test,Y_pred))

accuracy(test) : 0.262
              precision    recall  f1-score   support

           1       0.09      0.25      0.14        76
           2       0.13      0.24      0.17       120
           3       0.41      0.22      0.28       386
           4       0.38      0.33      0.35       333

    accuracy                           0.26       915
   macro avg       0.25      0.26      0.23       915
weighted avg       0.34      0.26      0.28       915



In [59]:
#1.변수선택
X = data[['bmi_g', 'height', 'weight', 'want_diet','weight_reduce', 'waist', 'heap']]
Y = data['p_category']

#2.데이터 전처리(preprocessing)
X = pd.get_dummies(X)

#3.train-test split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

#4.오버샘플링
smote=SMOTE(random_state=0)
X_train,Y_train=smote.fit_resample(X_train,Y_train)

#5.모형생성
model=GradientBoostingClassifier(random_state=0,n_estimators=100,max_depth=4,learning_rate=0.1)

#6.모형학습 예측
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
print("accuracy(test) : {:.3f}".format(model.score(X_test,Y_test)))
print(classification_report(Y_test,Y_pred))

accuracy(test) : 0.416
              precision    recall  f1-score   support

           1       0.28      0.45      0.34        76
           2       0.21      0.20      0.20       120
           3       0.50      0.59      0.54       386
           4       0.44      0.29      0.35       333

    accuracy                           0.42       915
   macro avg       0.35      0.38      0.36       915
weighted avg       0.42      0.42      0.41       915



In [60]:
# get feature importance
feature_importance = model.feature_importances_

# print the feature importance
for feature, importance in zip(X_train.columns, feature_importance):
    print("{}: {}".format(feature, importance))

bmi_g: 0.027178567031753517
height: 0.20537384764603328
weight: 0.10944121983132411
want_diet: 0.2757502976670159
weight_reduce: 0.18933638844331532
waist: 0.08674468912379663
heap: 0.10617499025676128
